### ISSUE TITLE
ExecuteContractFunction gives transaction error

### ISSUE THREAD

**Issue by MarlonDSC** [MoralisWeb3/unity-web3-game-kit#126]
![WhatsApp Image 2022-09-01 at 12 38 31 PM](https://user-images.githubusercontent.com/21266228/187967816-cb2e42f3-9035-4bd4-8fa2-488d8962d135.jpeg)
The latest SDK version cannot execute transactions. I've tried with 3 different projects, it doesn't execute the function with this version unfortunately. I've tried with the 1.2.2 version and it works with the 3 projects.

https://user-images.githubusercontent.com/21266228/187968322-08657526-7156-47e9-92f7-c75ec64410d6.mp4

**Comment by MarlonDSC** [comment]
> @MarlonDSC did you modify (add more gas) on the recent sdk version `ExecuteContractFunction`
> 
> try it again and before confirming the transaction, raise the gas a bit higher. and also make a video for it

Yes I did

**Comment by xactant** [comment]
@MarlonDSC Also make sure that you are meeting all permissions requirements in the contract method being called.

The RPC error is returned by the wallet due to:
1. Not enough gas
2. Incorrect parameter types
3. Execute permissions on the target contract / function for the wallet address
4. Asserts / conditions in the function that are not met by the wallet address / contract conditions / parameter values
