### ISSUE TITLE
No Information on Why UserObj.SaveAsync() Fails

### ISSUE THREAD

**Issue by vrxgaminginc** [MoralisWeb3/unity-web3-game-kit#99]
Get a MoralisUser in C#

user.username = "existing username"
user.email = "existing email"
bool result = await user.SaveAsync()

result will be false. but you do not know if the failure is due to username or email or both. in the JS SDK, an error is thrown, the error is not propogated to the C# API where it can be caught.

**Comment by xactant** [comment]
Do you see anything in your console log?

Did you create the user with:
```
MoralisUser user = Moralis.Create<MoralisUser>();
```

If not the user was not initialized to Moralis as it was created outside of Moralis. Please note that there are a set of changes that include an update to this process so that MoralisUser default constructor will initialize the user to Morlais.

That being said,  a more descriptive error response would be better than returning 'false'

**Comment by xactant** [comment]
Updated code to include save and a signIn exceptions that are thrown when the server reports a condition other than success.
